### ISSUE TITLE
create a system to count by blocks

### ISSUE THREAD

**Issue by adam-zethraeus** [cgiffard/Downsize#12]
status quo:
- downsize("", {words: #});
- downsize("", {characters: #});

suggested addition:
- downsize("", {blocks: 5, blockTypes:{"p","pre","blockquote","ul","li"}});

Intended as a generic version of paragraphs:5 or something, but that could be added as a good shortcut too.

What do you think?

**Comment by cgiffard** [comment]
I'm wondering whether a lot of this functionality might be serviced by a custom count function, like so:

``` javascript
downsize("...", function(token, stack, ...) {
    return true/false;
});
```

(Or perhaps the function would be better passed in through the options object.)

**Comment by adam-zethraeus** [comment]
Would this be as a substitute for actually implementing the functionality in downsize?
I guess it becomes a matter of you choosing the scope of the project then!

**Comment by cgiffard** [comment]
I also think giving downsize a better comprehension of the underlying HTML might make custom handling a little easier.

I'm going to add some contribution guidelines and make sure the documentation is clear — but once that's done, could I give you push access to this repo?

**Comment by adam-zethraeus** [comment]
That'd be awesome.

**Comment by cgiffard** [comment]
@zethraeus Does contextual tags satisfy this issue, or is there a deeper requirement here?

**Comment by adam-zethraeus** [comment]
satisfies. thanks for pointing it out
