### ISSUE TITLE
system to maintain initial image

### ISSUE THREAD

**Issue by adam-zethraeus** [cgiffard/Downsize#13]
What do you think would be a good API to preserve an initial image in the HTML?

  downsize("", {words:0, keepInitialImage:true});

**Comment by adam-zethraeus** [comment]
I'm going to start work on this today or tomorrow since it seems to be a blocker for merging anything new into ghost.

**Comment by cgiffard** [comment]
Sorry, I've been flat out. I'll have a think about the best way to tackle this tonight — let me know if you get started on it, so we don't end up double-handling. :)

**Comment by ErisDS** [comment]
Bump :) Would looove for this to be resolved even if it's just a temporary workaround with the condition that I remove it when Ghost no longer needs it :wink:

**Comment by adam-zethraeus** [comment]
i'll take another look shortly.

**Comment by adam-zethraeus** [comment]
next on my plate if the cleanup (https://github.com/cgiffard/Downsize/pull/16) goes in! :)

**Comment by adam-zethraeus** [comment]
It looks like the two cases this would have to deal with are markdown output matching:

`<p><img src="..." ...></p>`
and
`<p><a href="#"><img src=".."></a></p>`

**Comment by ErisDS** [comment]
It currently works for video as well I believe.

**Comment by adam-zethraeus** [comment]
oh good point, thanks!

**Comment by cgiffard** [comment]
I want to extend the parser to support tag types rather than regex it. If we merge this we should have a followup to do it properly. :)

**Comment by ErisDS** [comment]
I think you can close this issue now. I have a plan to reproduce this _feature_ inside Ghost, so that we can upgrade to a newer version of downsize. I don't think it's really the job of downsize to maintain what was a bug.

Also, by having it internally in Ghost, we can properly manage deprecating it once we have equivalent functionality done in the right way.
