### ISSUE TITLE
dupe functionality introduced with round=true api

### ISSUE THREAD

**Issue by adam-zethraeus** [cgiffard/Downsize#23]
https://github.com/cgiffard/Downsize/pull/22#issuecomment-54541754

**Comment by adam-zethraeus** [comment]
Also, if i'm wrong, or i'm just missing context for this decision (perhaps from the ghost side?) please just let me know!

**Comment by ErisDS** [comment]
@zethraeus there is some more context in the linked issue in express-hbs: https://github.com/barc/express-hbs/issues/66 and in this issue on Ghost: https://github.com/TryGhost/Ghost/issues/2163#issuecomment-54139521, but you're not missing anything critical as I also thought this was duplicate functionality.

I think having the sentence-terminating tags built in might be beneficial though?

**Comment by adam-zethraeus** [comment]
@ErisDS Thanks! I like the idea of having a default heuristic for sentence terminating tags too.

( @remy @cgiffard )

**Comment by cgiffard** [comment]
I'm closing this issue as I've merged @zethraeus's changes but it might be worth revisiting to make sure people are happy with the results. :)
